ALTER TABLE task
ADD mandayUsed INT NOT NULL
DEFAULT 0;

ALTER TABLE event
ADD type ENUM('ABSENCE',
	'LEAVE',
	'SICK_LEAVE',
	'FORMATION',
	'PROJECT_ENTRY',
	'PROJECT_EXIT',
	'MEETING',
	'OTHER')
;

CREATE TABLE IF NOT EXISTS ROLE(
	id INT NOT NULL AUTO_INCREMENT,
	role VARCHAR(50) NOT NULL UNIQUE,
	CONSTRAINT pk_role PRIMARY KEY(id)
)
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PROJECT_ROLES(
	id_project INT NOT NULL,
	id_role INT NOT NULL,
	PRIMARY KEY(id_project, id_role) ,
	CONSTRAINT fk_project_roles_employee FOREIGN KEY(id_project) REFERENCES PROJECT(id),
	CONSTRAINT fk_project_roles_role FOREIGN KEY(id_role) REFERENCES ROLE(id)
)
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS EMPLOYEES_PROJECTS(
	id_employee INT NOT NULL,
	id_project INT NOT NULL,
	id_role INT NOT NULL,
	PRIMARY KEY (id_employee, id_project) ,
	CONSTRAINT fk_employee_project FOREIGN KEY(id_employee) REFERENCES EMPLOYEE(id),
	CONSTRAINT fk_project_employee FOREIGN KEY(id_project) REFERENCES PROJECT(id),
	CONSTRAINT fk_project_role_employee FOREIGN KEY(id_project) REFERENCES ROLE(id)
)
ENGINE=InnoDB;

ALTER TABLE EMPLOYEE
ADD email VARCHAR(70) NOT NULL;

ALTER TABLE EMPLOYEE
ADD birthdate DATE;

ALTER TABLE EMPLOYEE
ADD phone VARCHAR(10) NOT NULL;

ALTER TABLE EMPLOYEE
ADD poste VARCHAR(40) NOT NULL;

ALTER TABLE EMPLOYEE
ADD UNIQUE (username);

ALTER TABLE PROJECT
ADD UNIQUE (name);