ALTER TABLE task
ADD mandayUsed INT NOT NULL
DEFAULT 0;

ALTER TABLE event
ADD type ENUM('ABSENCE',
	'LEAVE',
	'SICK_LEAVE',
	'FORMATION',
	'PROJECT_ENTRY',
	'PROJECT_EXIT',
	'MEETING',
	'OTHER')
;

CREATE TABLE EMPLOYEES_PROJECTS(
	id_employee INT NOT NULL,
	id_project INT NOT NULL,
	CONSTRAINT fk_employee_project FOREIGN KEY(id_employee) REFERENCES EMPLOYEE(id),
	CONSTRAINT fk_project_employee FOREIGN KEY(id_project) REFERENCES PROJECT(id)
)
ENGINE=InnoDB;

ALTER TABLE EMPLOYEE
ADD email VARCHAR(70) NOT NULL;

ALTER TABLE EMPLOYEE
ADD birthdate DATE;

ALTER TABLE EMPLOYEE
ADD phone VARCHAR(10) NOT NULL;

ALTER TABLE EMPLOYEE
ADD poste VARCHAR(40) NOT NULL;

ALTER TABLE EMPLOYEE
ADD UNIQUE (username);